### PR TITLE
add copy project to interface of logclient

### PR DESCRIPTION
**Pull request by wjo1212**
1. add copy project to interface of logclient
2. update logtail config to add logsample for all case
3. cover it in test case, pass in CI:
https://travis-ci.org/wjo1212/aliyun-log-python-sdk/builds/302013438

### CODE REVIEW

**Comment by wjo1212** [comment]
4. add interface of logclient to change the http user agent info (for CLI usage)

**Comment by wjo1212** [comment]
5. add interface: list project and fix some other bugs
pass CI: 
https://travis-ci.org/wjo1212/aliyun-log-python-sdk/builds/302306612

**Comment by wjo1212** [comment]
@zzboy

**Comment by zzboy** [comment]
测试通过就可以直接merge了，有些api的细节我也不是很清楚

**Pull request merged**
