### PR TITLE
fix bad loop for hard-shutdown check

### PR DESCRIPTION
**Pull request by songroger**
shard worker: add hard-shutdown is shutdown

### CODE REVIEW

**Comment by wjo1212** [comment]
@songroger thanks for submitting this PR. 

It seems the changes just return True for `is_complete` for heatbeat even it's still shutting down. To my understanding, the purpose is to make heatbeat shutdown faster, right? if so, the good news is: **I happened to make some improvement for the same purpose yesterday**: https://github.com/aliyun/aliyun-log-python-sdk/commit/5ab3dcfa44adfb2d81920a9f0f1870fe823c8e4d

it's been verified and updated to Pypi: 0.6.40.2, thus you recommend you try it first and let me if it could fulfill your requirements. Thanks!

**Comment by songroger** [comment]
No, it's another place. When the consumer [**'ShardConsumerWorker'**] trigger the func `shut_down` , it sets the flag and changes the status to "SHUTTING_DOWN", but seems wont change the status to "SHUTDOWN_COMPLETE" ? And the loop still check with `is_shutdown()`. So I think it's a dead loop for `shutdown_and_wait` or never happen for `clean_shard_consumer` to remove consumer.

**Comment by wjo1212** [comment]
@songroger thanks for the response. It seems previous code works  well, you could try the [4 new examples of consumer group lib](https://github.com/aliyun/aliyun-log-python-sdk/tree/master/tests/consumer_group_examples), there're also 3 articles describing them:
- [日志服务与SIEM（如Splunk）集成方案](https://aliyun-log-python-sdk.readthedocs.io/tutorials/tutorial_consumer_group_sync_log_to_splunk.html)
- [使用消费组实时分发数据](https://aliyun-log-python-sdk.readthedocs.io/tutorials/tutorial_consumer_group_dispatch_log.html)
- [使用消费组实时实时跨域监测多日志库数据](https://aliyun-log-python-sdk.readthedocs.io/tutorials/tutorial_consumer_group_monitor_multiple_logstores.html)

when you send close signal via `Ctrl+C`, the program exit quickly as expected.

**Comment by songroger** [comment]
@wjo1212 Thank you for your reply. 
Yes, `Ctrl+C` works. Just from the code algorithm, I'm still confused  how the inner loop `clean_shard_consumer` runs pop shard, because `is_shutdown` only return True for SHUTDOWN_COMPLETE, but the func `shut_down` only set to SHUTTING_DOWN . 
Maybe it changes the status to SHUTDOWN_COMPLETE always, but somewhere else I didn't see? 
Or maybe the part of the code is just useless?

**Comment by wjo1212** [comment]
@songroger yes, it will change it to SHUTDOWN_COMPLETE in `_update_satus`, refer to [code](https://github.com/aliyun/aliyun-log-python-sdk/blob/master/aliyun/log/consumer/shard_worker.py#L203) here.

**Comment by songroger** [comment]
@wjo1212 Yeah, I saw the `_update_status` before. To change it to SHUTDOWN_COMPLETE, it should fulfill two conditions, during the working `task_succcess` is False, `current_task_exist` I treat it True, so I'm confused.
If it will change it to SHUTDOWN_COMPLETE always,  I have  no doubt now. Thank you~

**Pull request closed without merging**
